/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DataRegistryStorageV1__factory } from "./DataRegistryStorageV1__factory";
export { IDataRegistry__factory } from "./IDataRegistry__factory";
