/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DataRegistryStorageV1 } from "./DataRegistryStorageV1";
export type { IDataRegistry } from "./IDataRegistry";
