/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { DataRegistryImplementation__factory } from "./DataRegistryImplementation__factory";
export { DataRegistryProxy__factory } from "./DataRegistryProxy__factory";
